# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /feedstock/recipe, last modified Wed Dec 18 14:44:56 2024
# ------------------------------------------------

package:
  name: attrs
  version: 24.3.0
source:
  sha256: 8f5c07333d543103541ba7be0e2ce16eeee8130cb0b3f9238ab904ce1e85baff
  url: https://pypi.io/packages/source/a/attrs/attrs-24.3.0.tar.gz
build:
  number: '0'
  script: python -m pip install . --no-deps --no-build-isolation -vv
  string: py312h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2024.11.26 h06a4308_0
    - expat 2.6.4 h6a678d5_0
    - hatch-fancy-pypi-readme 24.1.0 py312h06a4308_0
    - hatch-vcs 0.3.0 py312h06a4308_1
    - hatchling 1.27.0 py312h06a4308_0
    - ld_impl_linux-64 2.40 h12ee557_0
    - libffi 3.4.4 h6a678d5_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.15 h5eee18b_0
    - packaging 24.2 py312h06a4308_0
    - pathspec 0.10.3 py312h06a4308_0
    - pip 24.2 py312h06a4308_0
    - pluggy 1.5.0 py312h06a4308_0
    - python 3.12.8 h5148396_0
    - readline 8.2 h5eee18b_0
    - setuptools 75.1.0 py312h06a4308_0
    - setuptools-scm 8.1.0 py312h06a4308_0
    - sqlite 3.45.3 h5eee18b_0
    - tk 8.6.14 h39e8969_0
    - trove-classifiers 2024.10.14 py312h06a4308_0
    - tzdata 2024b h04d1e81_0
    - wheel 0.44.0 py312h06a4308_0
    - xz 5.4.6 h5eee18b_1
    - zlib 1.2.13 h5eee18b_1
  run:
    - python >=3.12,<3.13.0a0
test:
  commands:
    - pip check
    - pytest --fixtures tests -vv
  imports:
    - attr
  requires:
    - cloudpickle
    - hypothesis
    - mypy >=1.1.1
    - pip
    - psutil
    - pytest >=4.3.0
    - pytest-xdist
  source_files:
    - tests
about:
  description: 'attrs is the Python package that will bring back the joy of writing

    classes by relieving you from the drudgery of implementing object

    protocols (aka dunder methods). Its main goal is to help you to write

    concise and correct software without slowing down your code. For that, it

    gives you a class decorator and a way to declaratively define the

    attributes on that class:

    '
  dev_url: https://github.com/python-attrs/attrs
  doc_url: https://www.attrs.org/
  home: https://www.attrs.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: attrs is the Python package that will bring back the joy of writing classes
    by relieving you from the drudgery of implementing object protocols (aka dunder
    methods).
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 01dd36c2-f5e0-4781-9265-756ae10a516a
  recipe-maintainers:
    - CJ-Wright
    - jochym
    - licode
    - nicoddemus
  remote_url: git@github.com:AnacondaRecipes/attrs-feedstock.git
  sha: 2c91b4db14a450c888c90aa672574eb6f9341eaa
