# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /feedstock/recipe, last modified Wed Oct  9 15:11:30 2024
# ------------------------------------------------

package:
  name: jsonschema
  version: 4.23.0
source:
  patches:
    - patches/001-remove-fancy-pypi-readme.patch
  sha256: d71497fef26351a33265337fa77ffeb82423f3ea21283cd9467bb03999266bc4
  url: https://pypi.io/packages/source/j/jsonschema/jsonschema-4.23.0.tar.gz
build:
  entry_points:
    - jsonschema = jsonschema.cli:main
  number: '0'
  script: /croot/jsonschema_1728486696720/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . --no-deps --no-build-isolation -v
  string: py312h06a4308_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - patch 2.7.6 h7b6447c_1001
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2024.9.24 h06a4308_0
    - expat 2.6.3 h6a678d5_0
    - hatch-vcs 0.3.0 py312h06a4308_1
    - hatchling 1.25.0 py312h06a4308_0
    - ld_impl_linux-64 2.40 h12ee557_0
    - libffi 3.4.4 h6a678d5_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.15 h5eee18b_0
    - packaging 24.1 py312h06a4308_0
    - pathspec 0.10.3 py312h06a4308_0
    - pip 24.2 py312h06a4308_0
    - pluggy 1.0.0 py312h06a4308_1
    - python 3.12.7 h5148396_0
    - readline 8.2 h5eee18b_0
    - setuptools 75.1.0 py312h06a4308_0
    - setuptools-scm 8.1.0 py312h06a4308_0
    - sqlite 3.45.3 h5eee18b_0
    - tk 8.6.14 h39e8969_0
    - trove-classifiers 2023.10.18 py312h06a4308_0
    - tzdata 2024b h04d1e81_0
    - wheel 0.44.0 py312h06a4308_0
    - xz 5.4.6 h5eee18b_1
    - zlib 1.2.13 h5eee18b_1
  run:
    - attrs >=22.2.0
    - jsonschema-specifications >=2023.03.6
    - python >=3.12,<3.13.0a0
    - referencing >=0.28.4
    - rpds-py >=0.7.1
test:
  commands:
    - pip check
    - jsonschema --version
    - jsonschema --help
  imports:
    - jsonschema
  requires:
    - pip
about:
  description: 'jsonschema is an implementation of JSON Schema for Python

    '
  dev_url: https://github.com/python-jsonschema/jsonschema
  doc_url: https://python-jsonschema.readthedocs.io
  home: https://github.com/python-jsonschema/jsonschema
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: An implementation of JSON Schema validation for Python
extra:
  copy_test_source_files: true
  feedstock-name: jsonschema
  final: true
  flow_run_id: b1a299c9-4bc6-4cb8-b40e-c6e4a567c028
  recipe-maintainers:
    - bollwyvl
    - minrk
    - nehaljwani
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/jsonschema-feedstock.git
  sha: 22b36c618bf00cce1b38955c3445d857ff789b34
