# This file created by conda-build 3.27.0
# meta.yaml template originally from:
# /work/perseverance-python-buildout/aggregate/requests-toolbelt-feedstock/recipe, last modified Wed Nov  1 02:15:17 2023
# ------------------------------------------------

package:
  name: requests-toolbelt
  version: 1.0.0
source:
  sha256: 7681a0a3d047012b5bdc0ee37d7f8f07ebe76ab08caeccfc3921ce23c88d5bc6
  url: https://pypi.io/packages/source/r/requests-toolbelt/requests-toolbelt-1.0.0.tar.gz
build:
  number: '0'
  script: /work/perseverance-python-buildout/croot/requests-toolbelt_1698846872000/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . --no-deps --no-build-isolation -vv
  string: py312h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2023.08.22 h06a4308_0
    - expat 2.5.0 h6a678d5_0
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.4.4 h6a678d5_0
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.11 h7f8727e_2
    - pip 23.3 py312h06a4308_0
    - python 3.12.0 h996f2a0_0
    - readline 8.2 h5eee18b_0
    - setuptools 68.0.0 py312h06a4308_0
    - sqlite 3.41.2 h5eee18b_0
    - tk 8.6.12 h1ccaba5_0
    - tzdata 2023c h04d1e81_0
    - wheel 0.41.2 py312h06a4308_0
    - xz 5.4.2 h5eee18b_0
    - zlib 1.2.13 h5eee18b_0
  run:
    - python >=3.12,<3.13.0a0
    - requests >=2.0.1,<3.0.0
test:
  commands:
    - pip check
  imports:
    - requests_toolbelt
    - requests_toolbelt.adapters
    - requests_toolbelt.auth
    - requests_toolbelt.downloadutils
    - requests_toolbelt.multipart
    - requests_toolbelt.threaded
    - requests_toolbelt.utils
  requires:
    - pip
about:
  description: 'A toolbelt of useful classes and functions to be used with python-requests

    '
  dev_url: https://github.com/requests/toolbelt
  doc_url: https://toolbelt.readthedocs.io/
  home: https://toolbelt.readthedocs.io/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A toolbelt of useful classes and functions to be used with python-requests
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - sigmavirus24
