# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /feedstock/recipe, last modified Fri Jan 10 20:34:14 2025
# ------------------------------------------------

package:
  name: rpds-py
  version: 0.22.3
source:
  sha256: e32fee8ab45d3c2db6da19a5323bc3362237c8b653c70194414b892fd06a080d
  url: https://pypi.io/packages/source/r/rpds-py/rpds_py-0.22.3.tar.gz
build:
  missing_dso_whitelist: null
  number: '0'
  string: py312h4aa5aa6_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.40 h5293946_0
    - binutils_linux-64 2.40.0 hc2dff05_1
    - cargo-bundle-licenses 0.5.0 h52d8a92_0
    - gcc_impl_linux-64 11.2.0 h1234567_1
    - gcc_linux-64 11.2.0 h5c386dc_1
    - gxx_impl_linux-64 11.2.0 h1234567_1
    - gxx_linux-64 11.2.0 hc2dff05_1
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.40 h12ee557_0
    - libgcc-devel_linux-64 11.2.0 h1234567_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-devel_linux-64 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - rust 1.82.0 h6a678d5_0
    - rust_linux-64 1.82.0 h6a678d5_0
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2024.12.31 h06a4308_0
    - expat 2.6.4 h6a678d5_0
    - ld_impl_linux-64 2.40 h12ee557_0
    - libffi 3.4.4 h6a678d5_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - maturin 1.5.1 py312hb02cf49_1
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.15 h5eee18b_0
    - pip 24.2 py312h06a4308_0
    - python 3.12.8 h5148396_0
    - readline 8.2 h5eee18b_0
    - setuptools 75.1.0 py312h06a4308_0
    - sqlite 3.45.3 h5eee18b_0
    - tk 8.6.14 h39e8969_0
    - tzdata 2024b h04d1e81_0
    - wheel 0.44.0 py312h06a4308_0
    - xz 5.4.6 h5eee18b_1
    - zlib 1.2.13 h5eee18b_1
  run:
    - libgcc-ng >=11.2.0
    - python >=3.12,<3.13.0a0
test:
  commands:
    - pip check
    - pytest -v tests
  imports:
    - rpds
  requires:
    - pip
    - pytest
  source_files:
    - tests
about:
  description: Python bindings to Rust's persistent data structures (rpds)
  dev_url: https://github.com/crate-py/rpds
  doc_url: https://github.com/crate-py/rpds?tab=readme-ov-file#usage
  home: https://github.com/crate-py/rpds
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Python bindings to Rust's persistent data structures (rpds)
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 4a0c273e-60a3-4b66-a81a-94f8763c2d12
  recipe-maintainers:
    - bollwyvl
  remote_url: git@github.com:AnacondaRecipes/rpds-py-feedstock.git
  sha: e9644611d0834926f89d41e7ece725166fab9940
