# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /feedstock/recipe, last modified Wed Jun 19 17:31:31 2024
# ------------------------------------------------

package:
  name: jupyter_core
  version: 5.7.2
source:
  sha256: aa5f8d32bbf6b431ac830496da7392035d6f61b4f54872f15c4bd2a9c3f536d9
  url: https://pypi.io/packages/source/j/jupyter_core/jupyter_core-5.7.2.tar.gz
build:
  entry_points:
    - jupyter = jupyter_core.command:main
    - jupyter-migrate = jupyter_core.migrate:main
    - jupyter-troubleshoot = jupyter_core.troubleshoot:main
  number: '0'
  script: /croot/jupyter_core_1718818295206/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
    -m pip install . --no-deps --no-build-isolation -vv
  string: py312h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2024.3.11 h06a4308_0
    - editables 0.3 py312h06a4308_0
    - expat 2.6.2 h6a678d5_0
    - hatchling 1.21.1 py312h06a4308_0
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.4.4 h6a678d5_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.14 h5eee18b_0
    - packaging 23.2 py312h06a4308_0
    - pathspec 0.10.3 py312h06a4308_0
    - pip 24.0 py312h06a4308_0
    - pluggy 1.0.0 py312h06a4308_1
    - python 3.12.4 h5148396_1
    - readline 8.2 h5eee18b_0
    - setuptools 69.5.1 py312h06a4308_0
    - sqlite 3.45.3 h5eee18b_0
    - tk 8.6.14 h39e8969_0
    - trove-classifiers 2023.10.18 py312h06a4308_0
    - tzdata 2024a h04d1e81_0
    - wheel 0.43.0 py312h06a4308_0
    - xz 5.4.6 h5eee18b_1
    - zlib 1.2.13 h5eee18b_1
  run:
    - platformdirs >=2.5
    - python >=3.12,<3.13.0a0
    - traitlets >=5.3
test:
  commands:
    - pip check
    - jupyter -h
    - jupyter-migrate -h
    - jupyter-troubleshoot --help
    - pytest -vv -k "not (test_not_on_path or test_path_priority or test_argv0)"
  imports:
    - jupyter_core
    - jupyter_core.utils
  requires:
    - ipykernel
    - pip
    - pytest <8
    - pytest-timeout
  source_files:
    - pyproject.toml
    - tests
about:
  description: 'Jupyter core package. A base package on which Jupyter projects rely.

    This package contains base application classes and configuration inherited by
    other projects.

    '
  dev_url: https://github.com/jupyter/jupyter_core
  doc_url: https://jupyter-core.readthedocs.io
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Core common functionality of Jupyter projects.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 25f548e8-7333-4520-a956-5dfda3779492
  recipe-maintainers:
    - Carreau
    - bollwyvl
    - jakirkham
    - minrk
    - ocefpaf
    - pelson
  remote_url: git@github.com:AnacondaRecipes/jupyter_core-feedstock.git
  sha: f7993bd13fe1b7fc858430d7d35aa1f01278b037
